version: "3"
services:
    web:
        build: .
        ports: 
            - "10000:5000"
        volumes: 
            - "./flag:/flag:ro"
            - "./supervisord.conf:/etc/supervisord.conf"
        